ci: Filter go test output in real time
This way one doesn't have to wait for the tests to finish to see failures.

diff --git a/tools/bin/go_core_tests b/tools/bin/go_core_tests
--- a/tools/bin/go_core_tests
+++ b/tools/bin/go_core_tests
@@ -2,15 +2,10 @@
 set -o pipefail
 set +e
 
-go test -v -p 4 -parallel 4 ./... >./output.txt
-EXITCODE=$?
-
 echo "Failed tests and panics: ---------------------"
 echo ""
-grep --line-number --after-context=2 "panic: " output.txt
-echo ""
-grep --line-number "\-\-\- FAIL" output.txt
-grep -n "FAIL	" output.txt
+go test -v -p 4 -parallel 4 ./... | tee ./output.txt | grep --line-buffered --line-number --after-context=2 -e "panic: " -e "\-\-\- FAIL" -e "FAIL " -e "driver: bad connection"
+EXITCODE=$?
 echo ""
 echo "----------------------------------------------"
 
@@ -21,7 +16,6 @@ echo ""
 echo "Potentially related:"
 echo ""
 
-grep "driver: bad connection" output.txt
 echo "Exit code: $EXITCODE"
 if [[ $EXITCODE != 0 ]]; then
   echo "Encountered test failures."
