Use separate cleanup and exit_handler, trap INT

diff --git a/internal/ci/ethereum_test b/internal/ci/ethereum_test
--- a/internal/ci/ethereum_test
+++ b/internal/ci/ethereum_test
@@ -47,29 +47,6 @@ PATH=$SRCROOT/internal/bin:./node_modules/.bin:$PATH
 ECHO_SERVER_URL="http://localhost:6690/count"
 source $SRCROOT/internal/bin/clenv
 
-# Script cleanup and failure diagnosis helpers
-exit_handler() {
-  errno=$?
-  # Print all the logs if the test fails
-  if [ $errno -ne 0 ]; then
-    printf -- "\033[31mABORTING TEST!\033[0m\n"
-    printf -- "Exited with code $errno\n"
-    for log in $(find "$SRCROOT/integration" -maxdepth 1 -type f -iname '*.log'); do
-      printf -- "\n--------------------------------------------------------------------------------\n"
-      printf -- "\033[31m$log\033[0m\n"
-      printf -- "--------------------------------------------------------------------------------\n\n"
-      cat $log
-    done
-  fi
-  if [ -z "$CIRCLECI" ]; then
-    # Clear all signal handlers to prevent handler loop
-    trap - 1 2 3 15
-    # Kill all child subprocesses
-    pkill -P $$
-  fi
-  exit $errno
-}
-
 get_ethnet_version() {
   go get github.com/pelletier/go-toml/cmd/tomljson
   tomljson Gopkg.lock | jq -r '.projects | .[] | select(.name | contains("go-ethereum")) | .version'
@@ -182,7 +159,35 @@ launch_echo_server() {
   printf -- "\033[34mEcho server is running.\033[0m\n"
 }
 
-trap "exit_handler" EXIT SIGTERM SIGINT
+exit_handler() {
+  errno=$?
+  echo "EXIT_HANDLER"
+  # Print all the logs if the test fails
+  if [ $errno -ne 0 ]; then
+    printf -- "\033[31mABORTING TEST!\033[0m\n"
+    printf -- "Exited with code $errno\n"
+    for log in $(find "$SRCROOT/integration" -maxdepth 1 -type f -iname '*.log'); do
+      printf -- "\n--------------------------------------------------------------------------------\n"
+      printf -- "\033[31m$log\033[0m\n"
+      printf -- "--------------------------------------------------------------------------------\n\n"
+      cat $log
+    done
+  fi
+  cleanup
+  exit $errno
+}
+
+cleanup() {
+  if [ -n "$CIRCLECI" ]; then
+    return
+  fi
+
+  # Kill all child subprocesses
+  pkill -P $$
+}
+
+trap "exit_handler" EXIT
+trap "cleanup" SIGTERM SIGINT INT
 
 pushd $SRCROOT >/dev/null
 
