feat(ci): arm64 runners for unit tests

diff --git a/.github/actions/setup-solana/action.yml b/.github/actions/setup-solana/action.yml
--- a/.github/actions/setup-solana/action.yml
+++ b/.github/actions/setup-solana/action.yml
@@ -1,27 +1,81 @@
 name: Setup Solana CLI
 description: Setup solana CLI
 inputs:
-  base-path:
-    description: Path to the base of the repo
+  # version and installer checksum default values should
+  # be kept in sync with the values in tools/ci/install_solana
+  cli-version:
+    description: Version of solana CLI to install (e.g. v1.18.26)
     required: false
-    default: .
+    default: "v1.18.26"
+  installer-checksum:
+    description: Checksum of the solana CLI installer script
+    required: false
+    default: "cec72cde1cf36eb35cd8326245d23af0b6791fab68337c2953e2ca2a40af2c50"
+
+
 runs:
   using: composite
   steps:
-      - uses: actions/cache@v4
-        id: cache
-        name: Cache solana CLI
-        with:
-          path: |
-            ~/.local/share/solana/install/active_release/bin
-          key: ${{ runner.os }}-solana-cli-${{ hashFiles('${{ inputs.base-path }}tools/ci/install_solana') }}
-        
-      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
-        name: Install solana cli
-        shell: bash
-        working-directory: ${{ inputs.base-path }}
-        run: ./tools/ci/install_solana
-      
-      - name: Export solana path to env
-        shell: bash 
-        run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV
+    - name: Setup Path and Cache Key
+      id: setup
+      shell: bash
+      env:
+        CACHE_PATH: "~/.local/share/solana/install/active_release/bin"
+        CACHE_KEY: "${{ runner.os }}-${{ runner.arch }}-solana-cli-${{ inputs.cli-version }}-${{ hashFiles('tools/ci/install_solana') }}"
+      run: |
+        echo "cache-path=$CACHE_PATH" | tee -a $GITHUB_OUTPUT
+        echo "cache-key=$CACHE_KEY" | tee -a $GITHUB_OUTPUT
+
+    - name: Restore cached Solana CLI
+      uses: actions/cache/restore@v4
+      id: cache-restore
+      with:
+        path: ${{ steps.setup.outputs.cache-path }}
+        key: ${{ steps.setup.outputs.cache-key }}
+
+    - if: ${{ steps.cache-restore.outputs.cache-hit != 'true' && runner.arch != 'ARM64' }}
+      name: Install solana cli
+      shell: bash
+      env:
+        SOLANA_CLI_VERSION: ${{ inputs.cli-version }}
+        SOLANA_CLI_INSTALLER_CHECKSUM: ${{ inputs.installer-checksum }}
+      run: ./tools/ci/install_solana
+
+    - if: ${{ steps.cache-restore.outputs.cache-hit != 'true' && runner.arch == 'ARM64' }}
+      name: Build solana cli (arm64)
+      uses: ./.github/actions/setup-solana/build-solana-cli
+      with:
+        cli-version: ${{ inputs.cli-version }}
+
+    - name: Export solana path to env
+      shell: bash
+      env:
+        INSTALL_DIR: /home/runner/.local/share/solana/install/active_release/bin
+      run: |
+        echo "::group::Check install directory"
+        if [ -d "$INSTALL_DIR" ]; then
+          ls -la "$INSTALL_DIR"
+        else
+          echo "Directory $INSTALL_DIR does not exist"
+          exit 1
+        fi
+        echo "::endgroup::"
+
+        echo "::group::Add to path and verify"
+        export "PATH=$INSTALL_DIR:$PATH"
+        echo "PATH=$INSTALL_DIR:$PATH" >> $GITHUB_ENV
+
+        if ! command -v solana &> /dev/null
+        then
+          echo "::error::solana command was not found in PATH"
+          exit 1
+        fi
+        echo "::endgroup::"
+
+    # Save the cache immmediately so it is available even if the job fails afterwards
+    - name: Cache Solana CLI
+      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
+      uses: actions/cache/save@v4
+      with:
+        path: ${{ steps.setup.outputs.cache-path }}
+        key: ${{ steps.setup.outputs.cache-key }}
diff --git a/tools/ci/install_solana b/tools/ci/install_solana
--- a/tools/ci/install_solana
+++ b/tools/ci/install_solana
@@ -1,12 +1,23 @@
 #!/usr/bin/env bash
-
 set -euo pipefail
-VERSION=v1.18.26
-SHASUM=cec72cde1cf36eb35cd8326245d23af0b6791fab68337c2953e2ca2a40af2c50
 
-echo "Installing solana@${VERSION}"
-curl -sSfL https://release.anza.xyz/$VERSION/install --output install_solana.sh \
+if [ -z "${SOLANA_CLI_VERSION:-}" ] || [ -z "${SOLANA_CLI_INSTALLER_CHECKSUM:-}" ]; then
+    if [ -n "${CI:-}" ]; then
+        # if in CI and variables are not set, fail
+        echo "SOLANA_CLI_VERSION and SOLANA_CLI_INSTALLER_CHECKSUM must be set in CI"
+        exit 1
+    else
+        echo "SOLANA_CLI_VERSION and SOLANA_CLI_INSTALLER_CHECKSUM not set, using defaults"
+        SOLANA_CLI_VERSION="v1.18.26"
+        SOLANA_CLI_INSTALLER_CHECKSUM="cec72cde1cf36eb35cd8326245d23af0b6791fab68337c2953e2ca2a40af2c50"
+    fi
+fi
+
+echo "Using SOLANA_CLI_VERSION=${SOLANA_CLI_VERSION} and SOLANA_CLI_INSTALLER_CHECKSUM=${SOLANA_CLI_INSTALLER_CHECKSUM}"
+
+echo "Installing solana@${SOLANA_CLI_VERSION}"
+curl -sSfL https://release.anza.xyz/$SOLANA_CLI_VERSION/install --output install_solana.sh \
     && echo "Checking shasum of Solana install script." \
-    && echo "${SHASUM} install_solana.sh" | sha256sum --check
+    && echo "${SOLANA_CLI_INSTALLER_CHECKSUM} install_solana.sh" | sha256sum --check
 chmod +x install_solana.sh
 sh -c ./install_solana.sh
