wip

diff --git a/tools/ci/push_chainlink b/tools/ci/push_chainlink
--- a/tools/ci/push_chainlink
+++ b/tools/ci/push_chainlink
@@ -18,10 +18,10 @@ set -ex
 # Our registry, hosted on Public ECR.
 AWS_ECR_URL=public.ecr.aws/z0b1w9r9
 
-if [ -z "$DOCKERHUB_PASS" ]; then
-  echo "Cannot push to dockerhub, credentials are missing."
-  exit 1
-fi
+#if [ -z "$DOCKERHUB_PASS" ]; then
+#  echo "Cannot push to dockerhub, credentials are missing."
+#  exit 1
+#fi
 
 circle_branch="$1"
 circle_tag="$2"
