Update Docker build Make targets for integration-tests compatible with private deps

diff --git a/integration-tests/Makefile b/integration-tests/Makefile
--- a/integration-tests/Makefile
+++ b/integration-tests/Makefile
@@ -17,6 +17,7 @@ ifeq ($(UNAME_S),Darwin)
 		OSFLAG = $(OSX)
 endif
 endif
+comma := ,
 
 install_qa_tools:
 ifeq ($(OSFLAG),$(WINDOWS))
@@ -73,13 +74,16 @@ build_test_image:
 
 #Build a chainlink docker image for local testing and push to k3d registry
 .PHONY: build_push_docker_image
-build_push_docker_image:
-	docker build -f ../core/chainlink.Dockerfile --build-arg COMMIT_SHA=$(git rev-parse HEAD) --build-arg CHAINLINK_USER=chainlink -t 127.0.0.1:5000/chainlink:develop ../ ; docker push 127.0.0.1:5000/chainlink:develop
+build_push_docker_image: build_docker_image
+	docker tag $(image):$(tag) 127.0.0.1:5000/chainlink:develop
+	docker push 127.0.0.1:5000/chainlink:develop
 
 #Build a chainlink docker image in plugin mode for local testing and push to k3d registry
 .PHONY: build_push_plugin_docker_image
 build_push_plugin_docker_image:
-	docker build -f ../plugins/chainlink.Dockerfile --build-arg COMMIT_SHA=$(git rev-parse HEAD) --build-arg CHAINLINK_USER=chainlink -t 127.0.0.1:5000/chainlink:develop ../ ; docker push 127.0.0.1:5000/chainlink:develop
+	@echo "Run \"make docker-plugins\" from the root to build the chainlink-plugins (experimental) image."
+	@echo "After you run a build, you can push to your local docker registry with something like:"
+	@echo "docker push 127.0.0.1:5000/chainlink:develop"
 
 # Spins up containers needed to collect traces for local testing
 .PHONY: run_tracing
@@ -216,19 +220,26 @@ test_benchmark_automation: ## Run the automation benchmark tests
 test_reorg_automation: ## Run the automation reorg tests
 	go test -timeout 300m -v -run ^TestAutomationReorg$$ ./reorg -count=1 | tee automation_reorg_run_`date +"%Y%m%d-%H%M%S"`.log
 
+.PHONY: check_github_token
+check_github_token:
+	@if [ -z "$(GITHUB_TOKEN)" ]; then \
+		echo "Error: GITHUB_TOKEN environment variable to pull private dependencies. Try to set it via the gh cli: GITHUB_TOKEN=\$$(gh auth token)"; \
+		exit 1; \
+	fi
 # image: the name for the chainlink image being built, example: image=chainlink
 # tag: the tag for the chainlink image being built, example: tag=latest
 # example usage: make build_docker_image image=chainlink tag=latest
 .PHONY: build_docker_image
-build_docker_image:
-	docker build -f ../core/chainlink.Dockerfile --build-arg COMMIT_SHA=$(git rev-parse HEAD) --build-arg CHAINLINK_USER=chainlink -t $(image):$(tag) ../
+build_docker_image: check_github_token
+	docker build -f ../core/chainlink.Dockerfile \
+		--build-arg COMMIT_SHA=$(git rev-parse HEAD) \
+		--build-arg CHAINLINK_USER=chainlink \
+		--secret id=GIT_AUTH_TOKEN$(comma)env=GITHUB_TOKEN \
+		-t $(image):$(tag) ../
 
-# image: the name for the chainlink image being built, example: image=chainlink
-# tag: the tag for the chainlink image being built, example: tag=latest
-# example usage: make build_docker_image image=chainlink tag=latest
 .PHONY: build_plugin_docker_image
 build_plugin_docker_image:
-	docker build -f ../plugins/chainlink.Dockerfile --build-arg COMMIT_SHA=$(git rev-parse HEAD) --build-arg CHAINLINK_USER=chainlink -t 127.0.0.1:5000/chainlink:develop ../
+	@echo "Run \"make docker-plugins\" from the root to build the chainlink-plugins (experimental) image."
 
 # image: the name for the chainlink image being built, example: image=chainlink
 # tag: the tag for the chainlink image being built, example: tag=latest
