add a git_ref validation job

diff --git a/.github/workflows/build-publish-develop.yml b/.github/workflows/build-publish-develop.yml
--- a/.github/workflows/build-publish-develop.yml
+++ b/.github/workflows/build-publish-develop.yml
@@ -17,7 +17,21 @@ env:
   GIT_REF: ${{ github.event.inputs.git_ref || github.ref }}
 
 jobs:
+  validate-git-ref:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
+
+      - name: Validate GIT_REF
+        run: |
+          if ! git rev-parse --verify "${{ env.GIT_REF }}" > /dev/null 2>&1; then
+            echo "Invalid GIT_REF: ${{ env.GIT_REF }}"
+            exit 1
+          fi
+
   goreleaser-build-publish-chainlink:
+    needs: [validate-git-ref]
     runs-on:
       labels: ubuntu22.04-16cores-64GB
     environment: build-develop
@@ -37,7 +51,7 @@ jobs:
           role-duration-seconds: ${{ secrets.AWS_ROLE_DURATION_SECONDS }}
           aws-region: ${{ secrets.AWS_REGION }}
           mask-aws-account-id: true
-          role-session-name: build-publish-chainlink-develop
+          role-session-name: goreleaser-build-publish-chainlink
 
       - name: Build, sign, and publish image
         id: goreleaser-build-publish
