Add Send Flakeguard Main Test Report to Splunk workflow step

diff --git a/.github/workflows/ci-core.yml b/.github/workflows/ci-core.yml
--- a/.github/workflows/ci-core.yml
+++ b/.github/workflows/ci-core.yml
@@ -299,6 +299,39 @@ jobs:
           retention-days: 7
           if-no-files-found: ignore
 
+      - name: Install flakeguard
+        shell: bash
+        run: go install github.com/smartcontractkit/chainlink-testing-framework/tools/flakeguard@251c735bb9feb63190b7380ac61b2a3b1002c7b3 # flakguard@0.1.0
+  
+      - name: Send Flakeguard Main Test Report to Splunk
+        if: always()
+        shell: bash
+        run: |
+          # Fix flakeguard binary path
+          PATH=$PATH:$(go env GOPATH)/bin
+          export PATH
+
+          # Send the aggregated test report to Splunk
+          flakeguard send-to-splunk \
+            --report-path ${{ matrix.type.cmd }}_flakeguard_main_report.json \
+            --splunk-url "splunk.example.com" \
+            --splunk-token "${{ secrets.FLAKEGUARD_SPLUNK_HEC }}" \
+            --splunk-event "${{ github.event_name }}"
+            --repo-url "$GH_INPUTS_REPO_URL" \
+            --repo-path "${{ github.workspace }}" \
+            --codeowners-path "${{ github.workspace }}/.github/CODEOWNERS" \            
+            --branch-name "${{ github.head_ref || github.ref_name }}" \
+            --head-sha "${{ github.sha }}" \
+            --github-workflow-name "${{ github.workflow }}" \
+            --github-workflow-run-url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
+            --gen-report-id
+
+          EXIT_CODE=$?
+          if [ $EXIT_CODE -ne 0 ]; then
+            echo "ERROR: Flakeguard encountered an error while sending report to Splunk"
+            exit $EXIT_CODE
+          fi          
+
       - name: Print Races
         id: print-races
         if: ${{ failure() && matrix.type.cmd == 'go_core_race_tests' && matrix.type.should-run == 'true' }}
