feat(ci): transition to changed-modules-go

diff --git a/.github/workflows/ci-core.yml b/.github/workflows/ci-core.yml
--- a/.github/workflows/ci-core.yml
+++ b/.github/workflows/ci-core.yml
@@ -23,7 +23,7 @@ jobs:
     permissions:
       pull-requests: read
     outputs:
-      affected-modules: ${{ steps.resolved-modules.outputs.module_names }}
+      affected-modules: ${{ steps.changed-modules.outputs.modules-json }}
       # Runs on workflow changes, any deployment change, or any (non-ignored) core change
       should-run-deployment-tests: >-
         ${{
@@ -96,24 +96,9 @@ jobs:
             all:
               - '**'
 
-      - name: Resolve affected files to affected modules
-        id: resolved-modules
-        shell: bash
-        env:
-          GH_EVENT_NAME: ${{ github.event_name }}
-        run: |
-          # if scheduled, run for all modules (apart from the CRE workflow examples). Otherwise, run for only affected modules.
-          if [[ "$GH_EVENT_NAME" == "schedule" || "$GH_EVENT_NAME" == "workflow_dispatch" ]]; then
-            json_array=$(find . -name 'go.mod' -not -path './core/scripts/cre/environment/examples/workflows/*' -exec dirname {} \; | sed 's|^./||' | uniq |  jq -R -s -c 'split("\n") | map(select(length > 0))')
-            echo "module_names=$json_array" >> "$GITHUB_OUTPUT"
-          else
-            # Ensure the step uses `with.list-files: json` to get the list of files in JSON format
-            bash ./.github/scripts/map-affected-files-to-modules.sh '${{ steps.match-every.outputs.all_files }}' '["core/scripts/cre/environment/examples/workflows"]'
-          fi
-
       - name: Changed modules
+        id: changed-modules
         uses: smartcontractkit/.github/actions/changed-modules-go@changed-modules-go/v1
-        continue-on-error: true # don't let this call affect the outcome of the job (during rollout)
         with:
           # when scheduled/workflow_dispatch, run against all modules
           no-change-behaviour: all
@@ -160,7 +145,9 @@ jobs:
           go-directory: ${{ matrix.modules }}
 
       - name: Notify Slack
-        if: ${{ failure() && needs.run-frequency.outputs.one-per-day-frequency == 'true' }}
+        # Skip for now as it's always failing on scheduled runs
+        if: false
+        # if: ${{ failure() && needs.run-frequency.outputs.one-per-day-frequency == 'true' }}
         uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
         with:
           method: chat.postMessage
@@ -174,15 +161,40 @@ jobs:
   # Inclusive check: all (new) modules are analyzed, but no need to enable "required" checks for each one
   golangci-matrix-results-validation:
     name: lint
-    if: ${{ always() && needs.golangci.result != 'skipped' && !contains(join(github.event.pull_request.labels.*.name, ' '), 'allow-lint-issues') }}
-    needs: [golangci]
+    if: ${{ always() }}
+    needs: [filter, golangci]
     runs-on: ubuntu-latest
     steps:
       - name: Check Golangci-lint Matrix Results
-        if: ${{ needs.golangci.result != 'success' }}
+        env:
+          GOLANGCI_RESULT: ${{ needs.golangci.result }}
+          ALLOW_FAILURE: ${{ contains(join(github.event.pull_request.labels.*.name, ' '), 'allow-lint-issues') }}
+          SKIPPED: ${{ needs.filter.outputs.affected-modules == '[]' }}
         run: |
-          echo "At least one 'GolangCI Lint' matrix job failed. Check the failed lint jobs."
-          exit 1
+          if [[ "${GOLANGCI_RESULT}" == "success" ]]; then
+            echo "All 'GolangCI Lint' matrix jobs succeeded."
+            exit 0
+          fi
+
+          if [[ "${GOLANGCI_RESULT}" == "skipped" || "${SKIPPED}" == "true" ]]; then
+            echo "'GolangCI Lint' jobs were skipped."
+            exit 0
+          fi
+
+          if [[ "${ALLOW_FAILURE}" == "true" ]]; then
+            echo "Some 'GolangCI Lint' matrix jobs failed, but failures are allowed due to 'allow-lint-issues' label."
+            exit 0
+          fi
+
+          if [[ "${GOLANGCI_RESULT}" == "cancelled" ]]; then
+            echo "'GolangCI Lint' jobs were cancelled."
+            exit 1
+          fi
+
+          if [[ "${GOLANGCI_RESULT}" == "failure" ]]; then
+            echo "'GolangCI Lint' matrix jobs had failures."
+            exit 1
+          fi
 
   core:
     env:
