bump

diff --git a/.github/workflows/ci-core.yml b/.github/workflows/ci-core.yml
--- a/.github/workflows/ci-core.yml
+++ b/.github/workflows/ci-core.yml
@@ -292,10 +292,10 @@ jobs:
 
       - name: Install flakeguard
         shell: bash
-        run: go install github.com/smartcontractkit/chainlink-testing-framework/tools/flakeguard@7d381abbc4f7706be02f93a8af66c4dab50cd394 # flakguard@0.1.0
+        run: go install github.com/smartcontractkit/chainlink-testing-framework/tools/flakeguard@d551457817f6ee22030bfc223a0ac1a18b0f4ab1 # flakguard@0.1.0
   
       - name: Generate Flakeguard Main Test Report
-        if: always()
+        if: ${{ always() && matrix.type.cmd == 'go_core_tests'}}
         shell: bash
         run: |
           # Fix flakeguard binary path
@@ -321,7 +321,7 @@ jobs:
           fi
 
       - name: Upload Flakeguard Main Test Report as Artifact
-        if: always()
+        if: ${{ always() && matrix.type.cmd == 'go_core_tests'}}
         uses: actions/upload-artifact@v4
         with:
           name: ${{ matrix.type.cmd }}_flakeguard_report_main_test_report.json
@@ -329,26 +329,26 @@ jobs:
           retention-days: 7
           if-no-files-found: ignore          
 
-      - name: Send Flakeguard Main Test Report to Splunk
-        if: always()
-        shell: bash
-        run: |
-          # Fix flakeguard binary path
-          PATH=$PATH:$(go env GOPATH)/bin
-          export PATH
+      # - name: Send Flakeguard Main Test Report to Splunk
+      #   if: ${{ always() && matrix.type.cmd == 'go_core_tests'}}
+      #   shell: bash
+      #   run: |
+      #     # Fix flakeguard binary path
+      #     PATH=$PATH:$(go env GOPATH)/bin
+      #     export PATH
 
-          # Send the aggregated test report to Splunk
-          flakeguard send-to-splunk \
-            --report-path ${{ matrix.type.cmd }}_flakeguard_report/main/all-test-report.json \
-            --splunk-url "splunk.example.com" \
-            --splunk-token "${{ secrets.FLAKEGUARD_SPLUNK_HEC }}" \
-            --splunk-event "${{ github.event_name }}"
+      #     # Send the aggregated test report to Splunk
+      #     flakeguard send-to-splunk \
+      #       --report-path ${{ matrix.type.cmd }}_flakeguard_report/main/all-test-report.json \
+      #       --splunk-url "${{ secrets.FLAKEGUARD_SPLUNK_ENDPOINT }}" \
+      #       --splunk-token "${{ secrets.FLAKEGUARD_SPLUNK_HEC }}" \
+      #       --splunk-event "${{ github.event_name }}"
            
-          EXIT_CODE=$?
-          if [ $EXIT_CODE -ne 0 ]; then
-            echo "ERROR: Flakeguard encountered an error while sending report to Splunk"
-            exit $EXIT_CODE
-          fi          
+      #     EXIT_CODE=$?
+      #     if [ $EXIT_CODE -ne 0 ]; then
+      #       echo "ERROR: Flakeguard encountered an error while sending report to Splunk"
+      #       exit $EXIT_CODE
+      #     fi          
 
       - name: Print Races
         id: print-races
