fix the json validity check

diff --git a/.github/workflows/client-compatibility-tests.yml b/.github/workflows/client-compatibility-tests.yml
--- a/.github/workflows/client-compatibility-tests.yml
+++ b/.github/workflows/client-compatibility-tests.yml
@@ -396,7 +396,11 @@ jobs:
           DECODED_BASE64_TEST_LIST=$(echo $BASE64_TEST_LIST | base64 -d)
           echo "Decoded input:"
           echo "$DECODED_BASE64_TEST_LIST"
-          echo "$DECODED_BASE64_TEST_LIST" | base64 -d | jq .
+          is_valid=$(echo "$DECODED_BASE64_TEST_LIST" | jq . > /dev/null 2>&1; echo $?)
+          if [ "$is_valid" -ne 0 ]; then
+              echo "Invalid base64 input. Please provide a valid base64 encoded JSON list of tests."
+              exit 1
+          fi
           JOB_MATRIX_JSON=$(echo $DECODED_BASE64_TEST_LIST)
           echo "JOB_MATRIX_JSON=${JOB_MATRIX_JSON}" >> $GITHUB_ENV
       # testlistgenerator is a tool that builds a matrix of tests to run
