Run selected e2e tests in merge queue

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -232,7 +232,7 @@ jobs:
           AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
           dep_evm_sha: ${{ inputs.evm-ref }}
 
-  run-core-e2e-tests-workflow:
+  run-core-e2e-tests-in-pr:
     name: Run Core E2E Tests
     permissions:
       actions: read
@@ -271,7 +271,51 @@ jobs:
       AWS_API_GW_HOST_GRAFANA: ${{ secrets.AWS_API_GW_HOST_GRAFANA }}
       SLACK_BOT_TOKEN: ${{ secrets.QA_SLACK_API_KEY }}
 
-  run-ccip-e2e-tests-workflow:
+  run-core-e2e-tests-in-merge-queue:
+    name: Run Core E2E Tests In Merge Queue
+    permissions:
+      actions: read
+      checks: write
+      pull-requests: write
+      id-token: write
+      contents: read
+    needs: [build-chainlink, changes]
+    # Enable when done debugging
+    # if: ${{ github.event_name == 'merge_group' }} 
+    uses: ./.github/workflows/run-e2e-tests-reusable-workflow.yml
+    with:
+      workflow_name: Run Core E2E Tests In Merge Queue
+      chainlink_version: ${{ inputs.evm-ref || github.sha }}
+      chainlink_upgrade_version: ${{ github.sha }}
+      test_workflow: Merge Queue E2E Core Tests
+      upload_cl_node_coverage_artifact: true
+      upload_cl_node_coverage_artifact_prefix: cl_node_coverage_data_
+      enable_otel_traces_for_ocr2_plugins: ${{ contains(join(github.event.pull_request.labels.*.name, ' '), 'enable tracing') }}
+      # Notify Test Tooling team in slack when merge queue tests fail
+      slack_notification_after_tests: on_failure
+      slack_notification_after_tests_channel_id: "#team-test-tooling-internal"
+      slack_notification_after_tests_name: Core E2E Tests In Merge Queue
+    secrets:
+      QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
+      QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
+      QA_AWS_ACCOUNT_NUMBER: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}
+      QA_PYROSCOPE_INSTANCE: ${{ secrets.QA_PYROSCOPE_INSTANCE }}
+      QA_PYROSCOPE_KEY: ${{ secrets.QA_PYROSCOPE_KEY }}
+      QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }}
+      GRAFANA_INTERNAL_TENANT_ID: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
+      GRAFANA_INTERNAL_BASIC_AUTH: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
+      GRAFANA_INTERNAL_HOST: ${{ secrets.GRAFANA_INTERNAL_HOST }}
+      GRAFANA_INTERNAL_URL_SHORTENER_TOKEN: ${{ secrets.GRAFANA_INTERNAL_URL_SHORTENER_TOKEN }}
+      LOKI_TENANT_ID: ${{ secrets.LOKI_TENANT_ID }}
+      LOKI_URL: ${{ secrets.LOKI_URL }}
+      LOKI_BASIC_AUTH: ${{ secrets.LOKI_BASIC_AUTH }}
+      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      AWS_REGION: ${{ secrets.QA_AWS_REGION }}
+      AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN: ${{ secrets.AWS_OIDC_IAM_ROLE_VALIDATION_PROD_ARN }}
+      AWS_API_GW_HOST_GRAFANA: ${{ secrets.AWS_API_GW_HOST_GRAFANA }}
+      SLACK_BOT_TOKEN: ${{ secrets.QA_SLACK_API_KEY }}
+              
+  run-ccip-e2e-tests-in-pr:
     name: Run CCIP E2E Tests
     permissions:
       actions: read
@@ -314,12 +358,12 @@ jobs:
     if: always()
     name: ETH Smoke Tests
     runs-on: ubuntu-latest
-    needs: [lint-integration-tests, run-core-e2e-tests-workflow, run-ccip-e2e-tests-workflow]
+    needs: [lint-integration-tests, run-core-e2e-tests-in-pr, run-ccip-e2e-tests-in-pr, run-core-e2e-tests-in-merge-queue]
     steps:
       - name: Check Core test results
         id: check_core_results
         run: |
-          results='${{ needs.run-core-e2e-tests-workflow.outputs.test_results }}'
+          results='${{ needs.run-core-e2e-tests-in-pr.outputs.test_results }}'
           echo "Core test results:"
           echo "$results" | jq .
           
@@ -329,8 +373,8 @@ jobs:
       - name: Check CCIP test results
         id: check_ccip_results
         run: |
-          if [[ '${{ needs.run-ccip-e2e-tests-workflow.result }}' != 'skipped' ]]; then
-            results='${{ needs.run-ccip-e2e-tests-workflow.outputs.test_results }}'
+          if [[ '${{ needs.run-ccip-e2e-tests-in-pr.result }}' != 'skipped' ]]; then
+            results='${{ needs.run-ccip-e2e-tests-in-pr.outputs.test_results }}'
             echo "CCIP test results:"
             echo "$results" | jq .
           else
@@ -346,9 +390,13 @@ jobs:
           channel-id: "#team-test-tooling-internal"
           slack-message: ":x: :mild-panic-intensifies: Node Migration Tests Failed: \n${{ format('https://github.com/{0}/actions/runs/{1}', github.repository, github.run_id) }}\n${{ format('Notifying <!subteam^{0}|{0}>', secrets.GUARDIAN_SLACK_NOTIFICATION_HANDLE) }}"
 
-      - name: Fail the job if core tests not successful
-        if: always() && needs.run-core-e2e-tests-workflow.result == 'failure'
+      - name: Fail the job if core tests in PR not successful
+        if: always() && needs.run-core-e2e-tests-in-pr.result == 'failure'
         run: exit 1
+
+      - name: Fail the job if core tests in merge queue not successful
+        if: always() && needs.run-core-e2e-tests-in-merge-queue.result == 'failure'
+        run: exit 1        
 
       - name: Fail the job if lint not successful
         if: always() && needs.lint-integration-tests.result == 'failure'
@@ -357,7 +405,7 @@ jobs:
   cleanup:
     name: Clean up integration environment deployments
     if: always()
-    needs: [run-core-e2e-tests-workflow, run-ccip-e2e-tests-workflow]
+    needs: [run-core-e2e-tests-in-pr, run-ccip-e2e-tests-in-pr, run-core-e2e-tests-in-merge-queue]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repo
@@ -389,7 +437,7 @@ jobs:
   show-chainlink-node-coverage:
     name: Show Chainlink Node Go Coverage
     if: always()
-    needs: [run-core-e2e-tests-workflow, run-ccip-e2e-tests-workflow]
+    needs: [run-core-e2e-tests-in-pr, run-ccip-e2e-tests-in-pr, run-core-e2e-tests-in-merge-queue]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the repo
