Update check-e2e-test-results

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -307,19 +307,38 @@ jobs:
       
   check-e2e-test-results:
     if: always()
-    name: Check E2E test results
+    name: ETH Smoke Tests
     runs-on: ubuntu-latest
-    needs: run-core-e2e-tests-workflow
+    needs: [run-core-e2e-tests-workflow, run-ccip-e2e-tests-workflow]
     steps:
       - name: Check test results
         id: check_results
         run: |
-          test_results='${{ needs.run-core-e2e-tests-workflow.outputs.test_results }}'
-          echo "Test results:"
-          echo "$test_results" | jq .
+          core_combined_test_results='${{ needs.run-core-e2e-tests-workflow.outputs.combined_test_results }}'
+          echo "Core combined test results: $core_combined_test_results"
+          echo "core_combined_test_results=$core_combined_test_results" >> $GITHUB_OUTPUT
 
-          node_migration_tests_failed=$(echo $test_results | jq '[.[] | select(.id == "integration-tests/migration/upgrade_version_test.go:*" ) | select(.result != "success")] | length > 0')
+          core_detailed_test_results='${{ needs.run-core-e2e-tests-workflow.outputs.detailed_test_results }}'
+          echo "Core detailed test results:"
+          echo "$core_detailed_test_results" | jq .
+          
+          node_migration_tests_failed=$(echo $core_detailed_test_results | jq '[.[] | select(.id == "integration-tests/migration/upgrade_version_test.go:*" ) | select(.result != "success")] | length > 0')
           echo "node_migration_tests_failed=$node_migration_tests_failed" >> $GITHUB_OUTPUT
+
+          if [[ "${{ needs.run-ccip-e2e-tests-workflow.result }}" != 'skipped' ]]; then
+            ccip_combined_test_results='${{ needs.run-ccip-e2e-tests-workflow.outputs.combined_test_results }}'
+            echo "CCIP combined test results: $core_combined_test_results"
+            echo "ccip_combined_test_results=$ccip_combined_test_results" >> $GITHUB_OUTPUT
+
+            ccip_detailed_test_results='${{ needs.run-ccip-e2e-tests-workflow.outputs.detailed_test_results }}'
+            echo "CCIP detailed test results:"
+            echo "$ccip_detailed_test_results" | jq .
+          else
+            echo "CCIP tests were skipped."
+
+            ccip_combined_test_results="skipped"
+            echo "ccip_combined_test_results=$ccip_combined_test_results" >> $GITHUB_OUTPUT
+          fi
 
       - name: Send slack notification for failed migration tests
         if: steps.check_results.outputs.node_migration_tests_failed == 'true' && github.event_name != 'workflow_dispatch'
@@ -329,6 +348,14 @@ jobs:
         with:
           channel-id: "#team-test-tooling-internal"
           slack-message: ":x: :mild-panic-intensifies: Node Migration Tests Failed: \n${{ format('https://github.com/{0}/actions/runs/{1}', github.repository, github.run_id) }}\n${{ format('Notifying <!subteam^{0}|{0}>', secrets.GUARDIAN_SLACK_NOTIFICATION_HANDLE) }}"
+
+      - name: Fail the job if core tests failed
+        if: always()
+        run: |
+          if [[ "${{ steps.check_results.outputs.core_combined_test_results }}" != "success" ]]; then
+              echo "Core E2E tests failed"
+              exit 1
+          fi
 
   cleanup:
     name: Clean up integration environment deployments
@@ -365,7 +392,7 @@ jobs:
   show-chainlink-node-coverage:
     name: Show Chainlink Node Go Coverage
     if: always()
-    needs: [cleanup]
+    needs: [run-core-e2e-tests-workflow, run-ccip-e2e-tests-workflow]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout the repo
