uncomment eth-smoke-go-mod-cache

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -230,7 +230,7 @@ jobs:
           AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
           dep_evm_sha: ${{ inputs.evm-ref }}
 
-  call-run-e2e-tests-workflow:
+  run-e2e-tests-workflow:
     name: Run E2E Tests
     if: ${{ !contains(join(github.event.pull_request.labels.*.name, ' '), 'skip-smoke-tests') }}
     # environment: integration
@@ -271,12 +271,12 @@ jobs:
   check-e2e-test-results:
     name: Check E2E test results
     runs-on: ubuntu-latest
-    needs: call-run-e2e-tests-workflow
+    needs: run-e2e-tests-workflow
     steps:
       - name: Check test results
         id: check_results
         run: |
-          test_results='${{ needs.call-run-e2e-tests-workflow.outputs.test_results }}'
+          test_results='${{ needs.run-e2e-tests-workflow.outputs.test_results }}'
           echo "Test results:"
           echo "$test_results" | jq .
 
@@ -296,7 +296,7 @@ jobs:
   cleanup:
     name: Clean up integration environment deployments
     if: always()
-    needs: [call-run-e2e-tests-workflow]
+    needs: [run-e2e-tests-workflow]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repo
@@ -347,29 +347,29 @@ jobs:
 
   # Run the setup if the matrix finishes but this time save the cache if we have a cache hit miss
   # this will also only run if both of the matrix jobs pass
-  # eth-smoke-go-mod-cache:
-  #   environment: integration
-  #   needs: [eth-smoke-tests]
-  #   runs-on: ubuntu-latest
-  #   name: ETH Smoke Tests Go Mod Cache
-  #   continue-on-error: true
-  #   steps:
-  #     - name: Checkout the repo
-  #       uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
-  #       with:
-  #         repository: smartcontractkit/chainlink
-  #         ref: ${{ inputs.cl_ref || github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
-  #     - name: Run Setup
-  #       uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/setup-go@75a9005952a9e905649cfb5a6971fd9429436acd # v2.3.25
-  #       with:
-  #         test_download_vendor_packages_command: |
-  #           cd ./integration-tests
-  #           go mod download
-  #           # force download of test dependencies
-  #           go test -run=NonExistentTest ./smoke/... || echo "ignore expected test failure"
-  #         go_mod_path: ./integration-tests/go.mod
-  #         cache_key_id: core-e2e-${{ env.MOD_CACHE_VERSION }}
-  #         cache_restore_only: "false"
+  eth-smoke-go-mod-cache:
+    environment: integration
+    needs: [run-e2e-tests-workflow]
+    runs-on: ubuntu-latest
+    name: ETH Smoke Tests Go Mod Cache
+    continue-on-error: true
+    steps:
+      - name: Checkout the repo
+        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
+        with:
+          repository: smartcontractkit/chainlink
+          ref: ${{ inputs.cl_ref || github.event.pull_request.head.sha || github.event.merge_group.head_sha }}
+      - name: Run Setup
+        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/setup-go@75a9005952a9e905649cfb5a6971fd9429436acd # v2.3.25
+        with:
+          test_download_vendor_packages_command: |
+            cd ./integration-tests
+            go mod download
+            # force download of test dependencies
+            go test -run=NonExistentTest ./smoke/... || echo "ignore expected test failure"
+          go_mod_path: ./integration-tests/go.mod
+          cache_key_id: core-e2e-${{ env.MOD_CACHE_VERSION }}
+          cache_restore_only: "false"
 
   ## Solana Section
   get_solana_sha:
