Add integration-tests/migration/upgrade_version_test.go:*

diff --git a/.github/workflows/run-e2e-tests-reusable-workflow.yml b/.github/workflows/run-e2e-tests-reusable-workflow.yml
--- a/.github/workflows/run-e2e-tests-reusable-workflow.yml
+++ b/.github/workflows/run-e2e-tests-reusable-workflow.yml
@@ -77,7 +77,12 @@ on:
 env: 
   CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
   QA_CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
+  GITHUB_SHA_PLUGINS: ${{ github.sha }}-plugins
+  CHAINLINK_ENV_USER: ${{ github.actor }}
+  CHAINLINK_COMMIT_SHA: ${{ inputs.evm-ref || github.sha }}
+  SELECTED_NETWORKS: SIMULATED
   MOD_CACHE_VERSION: 1
+  TEST_LOG_LEVEL: debug
 
 jobs:
   validate-inputs:
@@ -125,7 +130,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           repository: 'smartcontractkit/chainlink-testing-framework'
-          ref: 35aa2ea0837aee32466f735a8d2220fb413413c6
+          ref: e7d83b97f9c1aa6c94c133f0b21d578fd0075560
           path: 'chainlink-testing-framework'          
       - name: Setup Go
         uses: ./.github/actions/setup-go
@@ -135,10 +140,30 @@ jobs:
             echo "::error::Some E2E test configurations have to be added to .github/e2e-tests.yml. This file defines Github CI configuration for each E2E test or set of E2E tests." && exit 1
           fi
 
+  get_latest_chainlink_release_version:
+    name: Get latest Chainlink release version
+    runs-on: ubuntu-latest
+    environment: integration
+    outputs:
+      latest_chainlink_release_version: ${{ steps.get_latest_version.outputs.latest_version }}
+    steps:
+      - name: Get Latest Version
+        id: get_latest_version
+        run: |
+          untrimmed_ver=$(curl --header "Authorization: token ${{ secrets.GH_TOKEN }}" --request GET https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .name)
+          latest_version="${untrimmed_ver:1}"
+          echo "Latest Chainlink release version: $latest_version"
+          echo "latest_version=${latest_version}" >> "$GITHUB_OUTPUT"
+          # Check if latest_version is empty
+          if [ -z "$latest_version" ]; then
+          echo "Error: The latest_version is empty. The migration tests need a verison to run."
+          exit 1
+          fi
+
   load-test-configurations:
     name: Load test configurations
+    needs: [validate-inputs]
     runs-on: ubuntu-latest
-    needs: validate-inputs
     outputs:
       run-docker-tests: ${{ steps.check-matrices.outputs.run-docker-tests }}
       run-k8s-tests: ${{ steps.check-matrices.outputs.run-k8s-tests }}
@@ -151,7 +176,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           repository: 'smartcontractkit/chainlink-testing-framework'
-          ref: 35aa2ea0837aee32466f735a8d2220fb413413c6
+          ref: e7d83b97f9c1aa6c94c133f0b21d578fd0075560
           path: 'chainlink-testing-framework'        
       - name: Setup Go
         uses: ./.github/actions/setup-go
@@ -322,7 +347,7 @@ jobs:
   # Run Docker tests
   docker-tests:
     name: Run docker tests (${{ matrix.tests.id }})
-    needs: [load-test-configurations, require-chainlink-image-versions-in-qa-ecr, require-chainlink-plugin-versions-in-qa-ecr]
+    needs: [load-test-configurations, require-chainlink-image-versions-in-qa-ecr, require-chainlink-plugin-versions-in-qa-ecr, get_latest_chainlink_release_version]
     # Run when none of the needed jobs fail or are cancelled (skipped or successful jobs are ok) 
     if: ${{ needs.load-test-configurations.outputs.run-docker-tests == 'true' && always() && !failure() && !cancelled() }} 
     runs-on: ${{ matrix.tests.runsOn }}
@@ -337,10 +362,7 @@ jobs:
       id-token: write
       contents: read
     env:
-      SELECTED_NETWORKS: SIMULATED
-      CHAINLINK_ENV_USER: ${{ github.actor }}
-      TEST_LOG_LEVEL: debug
-      QA_CHAINLINK_IMAGE: ${{ secrets.QA_AWS_ACCOUNT_NUMBER }}.dkr.ecr.${{ secrets.QA_AWS_REGION }}.amazonaws.com/chainlink
+      LATEST_CHAINLINK_RELEASE_VERSION: ${{ needs.get_latest_chainlink_release_version.outputs.latest_chainlink_release_version }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
@@ -356,8 +378,8 @@ jobs:
         if: inputs.test_config_override_base64 == ''
         uses: ./.github/actions/create-default-e2e-config-override
         with:
-          chainlink_version: ${{ inputs.chainlink_version || matrix.tests.test_inputs.chainlinkVersion || github.sha }}
-          chainlink_upgrade_version: ${{ matrix.tests.test_inputs.chainlinkUpgradeVersion || 'develop' }} # Set default upgrade version
+          chainlink_version: ${{ inputs.chainlink_version || matrix.tests.test_inputs.chainlink_version || github.sha }}
+          chainlink_upgrade_version: ${{ matrix.tests.test_inputs.chainlink_upgrade_version || 'develop' }} # Set default upgrade version
           chainlink_postgres_version: ${{ matrix.tests.test_inputs.chainlinkPostgresVersion }}
           selected_networks: ${{ matrix.tests.test_inputs.selectedNetworks || env.SELECTED_NETWORKS}}
           logging_run_id: ${{ github.run_id }}
@@ -381,7 +403,7 @@ jobs:
           duplicate-authorization-header: "true"
 
       - name: Run tests
-        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@25e7c69bb6aae9781fec32355c6f9c485b12e594 # TODO: Create tag and use it here
+        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@6079d91c48cb08c686ea6dd53a047a36af9151f5 # TODO: Create tag and use it here
         env:
           DETACH_RUNNER: true
         with:
@@ -405,8 +427,8 @@ jobs:
           should_tidy: "false"
           go_coverage_src_dir: /var/tmp/go-coverage
           go_coverage_dest_dir: ${{ github.workspace }}/.covdata
-          DEFAULT_CHAINLINK_IMAGE: ${{ matrix.tests.test_inputs.chainlinkImage || env.CHAINLINK_IMAGE }}
-          DEFAULT_CHAINLINK_UPGRADE_IMAGE: ${{ matrix.tests.test_inputs.chainlinkUpgradeImage }}
+          DEFAULT_CHAINLINK_IMAGE: ${{ matrix.tests.test_inputs.chainlink_image || env.CHAINLINK_IMAGE }}
+          DEFAULT_CHAINLINK_UPGRADE_IMAGE: ${{ matrix.tests.test_inputs.chainlink_upgrade_image }}
           DEFAULT_LOKI_TENANT_ID: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
           DEFAULT_LOKI_ENDPOINT: https://${{ secrets.GRAFANA_INTERNAL_HOST }}/loki/api/v1/push
           DEFAULT_LOKI_BASIC_AUTH: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
@@ -456,7 +478,7 @@ jobs:
           fi
 
   run-k8s-runner-tests:
-    needs: [load-test-configurations, prepare-remote-runner-test-image, require-chainlink-image-versions-in-qa-ecr, require-chainlink-plugin-versions-in-qa-ecr]
+    needs: [load-test-configurations, prepare-remote-runner-test-image, require-chainlink-image-versions-in-qa-ecr, require-chainlink-plugin-versions-in-qa-ecr, get_latest_chainlink_release_version]
     if: ${{ needs.load-test-configurations.outputs.run-k8s-tests == 'true' && always() && !failure() && !cancelled() }} 
     name: Run k8s tests (${{ matrix.tests.id }})
     runs-on: ${{ matrix.tests.runsOn }}
@@ -471,11 +493,7 @@ jobs:
       id-token: write
       contents: read
     env:
-      SELECTED_NETWORKS: SIMULATED
-      CHAINLINK_COMMIT_SHA: ${{ inputs.evm-ref || github.sha }}
-      CHAINLINK_ENV_USER: ${{ github.actor }}
-      TEST_LOG_LEVEL: debug
-
+      LATEST_CHAINLINK_RELEASE_VERSION: ${{ needs.get_latest_chainlink_release_version.outputs.latest_chainlink_release_version }}      
     steps:
       - name: Checkout repository
         uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
@@ -492,8 +510,8 @@ jobs:
         if: inputs.test_config_override_base64 == ''
         uses: ./.github/actions/create-default-e2e-config-override
         with:
-          chainlink_version: ${{ inputs.chainlink_version || matrix.tests.test_inputs.chainlinkVersion || github.sha }}
-          chainlink_upgrade_version: ${{ matrix.tests.test_inputs.chainlinkUpgradeVersion || 'develop' }} # Set default upgrade version
+          chainlink_version: ${{ inputs.chainlink_version || matrix.tests.test_inputs.chainlink_version || github.sha }}
+          chainlink_upgrade_version: ${{ matrix.tests.test_inputs.chainlink_upgrade_version || 'develop' }} # Set default upgrade version
           chainlink_postgres_version: ${{ matrix.tests.test_inputs.chainlinkPostgresVersion }}
           selected_networks: ${{ matrix.tests.test_inputs.selectedNetworks || env.SELECTED_NETWORKS}}
           logging_run_id: ${{ github.run_id }}
@@ -508,7 +526,7 @@ jobs:
           echo "BASE64_CONFIG_OVERRIDE=$BASE64_CONFIG_OVERRIDE" >> $GITHUB_ENV              
 
       - name: Run tests
-        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@25e7c69bb6aae9781fec32355c6f9c485b12e594 # TODO: Create tag and use it here24
+        uses: smartcontractkit/chainlink-github-actions/chainlink-testing-framework/run-tests@6079d91c48cb08c686ea6dd53a047a36af9151f5 # TODO: Create tag and use it here24
         env:
           DETACH_RUNNER: true
           RR_MEM: ${{ matrix.tests.remoteRunnerMemory }}
@@ -533,8 +551,8 @@ jobs:
           QA_AWS_REGION: ${{ secrets.QA_AWS_REGION }}
           QA_AWS_ROLE_TO_ASSUME: ${{ secrets.QA_AWS_ROLE_TO_ASSUME }}
           QA_KUBECONFIG: ${{ secrets.QA_KUBECONFIG }} 
-          DEFAULT_CHAINLINK_IMAGE: ${{ matrix.tests.test_inputs.chainlinkImage || env.CHAINLINK_IMAGE }}
-          DEFAULT_CHAINLINK_UPGRADE_IMAGE: ${{ matrix.tests.test_inputs.chainlinkUpgradeImage }}
+          DEFAULT_CHAINLINK_IMAGE: ${{ matrix.tests.test_inputs.chainlink_image || env.CHAINLINK_IMAGE }}
+          DEFAULT_CHAINLINK_UPGRADE_IMAGE: ${{ matrix.tests.test_inputs.chainlink_upgrade_image }}
           DEFAULT_LOKI_TENANT_ID: ${{ secrets.GRAFANA_INTERNAL_TENANT_ID }}
           DEFAULT_LOKI_ENDPOINT: https://${{ secrets.GRAFANA_INTERNAL_HOST }}/loki/api/v1/push
           DEFAULT_LOKI_BASIC_AUTH: ${{ secrets.GRAFANA_INTERNAL_BASIC_AUTH }}
