feat: refactor ci core / solidity to support merge queue

diff --git a/.github/workflows/solidity.yml b/.github/workflows/solidity.yml
--- a/.github/workflows/solidity.yml
+++ b/.github/workflows/solidity.yml
@@ -161,10 +161,19 @@ jobs:
 
   solidity:
     needs: [changes, solidity-splits]
+    if: always()
     name: Solidity
     runs-on: ubuntu-latest
     steps:
       - run: echo 'Solidity tests finished!'
+      - name: Check test results
+        run: |
+          if [[ "${{ needs.changes.result }}" == "failure" || "${{ needs.solidity-splits.result }}" == "failure" ]]; then
+            echo "One or more changes / solidity-splits jobs failed"
+            exit 1
+          else
+            echo "All test jobs passed successfully"
+          fi
 
   prepublish-test:
     needs: [changes]
