remove extra changeset

diff --git a/.github/workflows/solidity-tracability.yml b/.github/workflows/solidity-tracability.yml
--- a/.github/workflows/solidity-tracability.yml
+++ b/.github/workflows/solidity-tracability.yml
@@ -32,7 +32,7 @@ jobs:
           # This is a valid input, see https://github.com/dorny/paths-filter/pull/226
           predicate-quantifier: "every"
           filters: |
-            source: 
+            source:
               - contracts/**/*.sol
               - '!contracts/**/*.t.sol'
             changesets:
@@ -95,7 +95,7 @@ jobs:
         uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
         with:
           repository: smartcontractkit/.github
-          ref: b6e37806737eef87e8c9137ceeb23ef0bff8b1db # validate-solidity-artifacts@0.1.0
+          ref: c3b25a0d5dcca20736fd02106771a9937bc35eff
           path: ./dot_github
 
       # we need to set the top level directory for the jira-tracing action manually
@@ -129,12 +129,17 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Enforce Solidity Review Jira issue
-        working-directory: ./.github/scripts/jira
+        working-directory: ./dot_github
+        shell: bash
         run: |
           # we do not want to fail the workflow if there are issues with the script
-          pnpm issue:enforce-solidity-review || true
+          if ! pnpm --filter jira-tracing issue:enforce-solidity-review; then
+            echo "::warning::Failed to enforce Solidity Review Jira issue, this is not a blocking issue. You can safely ignore it."
+          fi
         env:
           CHANGESET_FILES: ${{ needs.files-changed.outputs.changesets_files }}
+          GIT_TOP_LEVEL_DIR: ${{ steps.find-git-top-level-dir.outputs.top_level_dir }}
+
           SOLIDITY_REVIEW_TEMPLATE_KEY: 'TT-1634'
           EXPORT_JIRA_ISSUE_KEYS: 'true'
 
