add missing prompt; do not replace report with diff if empty

diff --git a/.github/workflows/solidity-foundry.yml b/.github/workflows/solidity-foundry.yml
--- a/.github/workflows/solidity-foundry.yml
+++ b/.github/workflows/solidity-foundry.yml
@@ -386,11 +386,11 @@ jobs:
         run: |
           for original_file in contracts/slither-reports-base-ref/*.md; do
             base_file=$(basename "$original_file")
-            new_file="contracts/slither-reports-current/$base_file"
+            current_file="contracts/slither-reports-current/$base_file"
             diff_file="contracts/slither-reports-current/${base_file%.md}_diff.md"
-            if [ -f "$new_file" ]; then
+            if [ -f "$current_file" ]; then
               report1=$(cat $original_file | sed -E 's/\\+$//g' | sed -E 's/\\+ //g')
-              report2=$(cat $new_file | sed -E 's/\\+$//g' | sed -E 's/\\+ //g')
+              report2=$(cat $current_file | sed -E 's/\\+$//g' | sed -E 's/\\+ //g')
               openai_prompt=$(cat contracts/scripts/ci/prompt.md | sed 's/"/\\"/g' | sed -E 's/\\+$//g' | sed -E 's/\\+ //g')
               openai_model="gpt-4o-mini"
               openai_result=$(echo '{
@@ -412,22 +412,26 @@ jobs:
           
               # throw error openai_result when is not 200
               if [ "$openai_result" != '200' ]; then
-              echo "::error::OpenAI API call failed with status $openai_result: $(cat prompt_response.json)"
-              exit 1
+                echo "::error::OpenAI API call failed with status $openai_result: $(cat prompt_response.json)"
+                exit 1
               fi
           
               # replace lines starting with ' -' (1space) with '  -' (2spaces)
               response_content=$(cat prompt_response.json | jq -r '.choices[0].message.content')
               echo "$response_content" | sed -e 's/^ -/  -/g' > $diff_file
           
-              awk 'NR==2{print "*This diff has been automatically generated by LLM model using two Slither reports. One based on `${{ github.base_ref}}` and another on `${{ github.sha }}` commits.*"}1' $diff_file > tmp.md && mv tmp.md $diff_file
-          
-              echo "Replacing full Slither report with diff for $new_file"
-          
-              rm $new_file
-              mv $diff_file $new_file
+              if [ -s $diff_file ]; then    
+                awk 'NR==2{print "*This diff has been automatically generated by LLM model using two Slither reports. One based on `${{ github.base_ref}}` and another on `${{ github.sha }}` commits.*"}1' $diff_file > tmp.md && mv tmp.md $diff_file
+              
+                cat $diff_file
+                    
+                echo "Replacing full Slither report with diff for $current_file"            
+                rm $current_file && mv $diff_file $current_file
+              else 
+                echo "No difference detected between $original_file and $current_file reports. Won't include any of them."
+              fi
             else
-              echo "File $new_file does not exist, skipping diff."
+              echo "File $current_file does not exist, skipping diff."
               #TODO check with git diff if it indeed was deleted?
             fi
           done        
